# Generated by Django 3.2.5 on 2022-03-31 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=45, unique=True)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45, unique=True)),
                ('last_name', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars_rating', models.IntegerField(unique=True)),
                ('comment', models.CharField(default='', max_length=250, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='restaurantreview.item')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='restaurantreview.reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_number', models.IntegerField(unique=True)),
                ('street_name', models.CharField(max_length=45, unique=True)),
                ('city', models.CharField(max_length=45, unique=True)),
                ('zipcode', models.IntegerField(unique=True)),
                ('state', models.CharField(max_length=25, unique=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='restaurantreview.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Dine',
            fields=[
                ('dine_at_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dines', to='restaurantreview.location')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dines', to='restaurantreview.reviewer')),
            ],
        ),
    ]
