# Generated by Django 3.2.5 on 2022-04-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dine',
            options={'ordering': ['date', 'location', 'reviewer']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name', 'item_cost']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['street_number', 'street_name']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['stars_rating']},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
        migrations.AddField(
            model_name='reviewer',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddConstraint(
            model_name='dine',
            constraint=models.UniqueConstraint(fields=('date', 'location'), name='unique_rating'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('street_number', 'street_name', 'city', 'state'), name='unique_location'),
        ),
        migrations.AddConstraint(
            model_name='reviewer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'middle_name'), name='unique_person'),
        ),
    ]
