# Generated by Django 3.2.5 on 2022-04-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantreview', '0004_auto_20220416_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.IntegerField(max_length=10),
        ),
    ]
