# Generated by Django 3.2.5 on 2022-04-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantreview', '0005_alter_location_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars_rating',
            field=models.IntegerField(max_length=2),
        ),
    ]
