# Generated by Django 3.2.5 on 2022-05-01 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantreview', '0006_alter_rating_stars_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
