from django.urls import path

from restaurantreview.views import (
    ReviewerList, RestaurantList, DineList, ItemList, LocationList, RatingList, RecipeList, RestaurantDetail,
    DineDetail, ItemDetail, LocationDetail, RatingDetail, ReviewerDetail, RecipeDetail, DineCreate, ItemCreate,
    RatingCreate, ReviewerCreate, RestaurantCreate, LocationCreate, RecipeCreate, ReviewerDelete, RestaurantDelete,
    LocationDelete, RecipeDelete, DineDelete, ItemDelete, RatingDelete, DineUpdate, ReviewerUpdate, RestaurantUpdate,
    ItemUpdate, LocationUpdate, RecipeUpdate, RatingUpdate,
)

urlpatterns = [
    path('reviewer/',
         ReviewerList.as_view(),
         name='restaurantreview_reviewer_list_urlpattern'),
    path('reviewer/<int:pk>/',
         ReviewerDetail.as_view(),
         name='restaurantreview_reviewer_detail_urlpattern'),
    path('reviewer/create/',
         ReviewerCreate.as_view(),
         name='restaurantreview_reviewer_create_urlpattern'),
    path('reviewer/<int:pk>/delete/',
         ReviewerDelete.as_view(),
         name='restaurantreview_reviewer_delete_urlpattern'),
    path('reviewer/<int:pk>/update/',
         ReviewerUpdate.as_view(),
         name='restaurantreview_reviewer_update_urlpattern'),
    path('restaurant/',
         RestaurantList.as_view(),
         name='restaurantreview_restaurant_list_urlpattern'),
    path('restaurant/<int:pk>/',
         RestaurantDetail.as_view(),
         name='restaurantreview_restaurant_detail_urlpattern'),
    path('restaurant/create/',
         RestaurantCreate.as_view(),
         name='restaurantreview_restaurant_create_urlpattern'),
    path('restaurant/<int:pk>/delete/',
         RestaurantDelete.as_view(),
         name='restaurantreview_restaurant_delete_urlpattern'),
    path('restaurant/<int:pk>/update/',
         RestaurantUpdate.as_view(),
         name='restaurantreview_restaurant_update_urlpattern'),
    path('dine/',
         DineList.as_view(),
         name='restaurantreview_dine_list_urlpattern'),
    path('dine/<int:pk>/',
         DineDetail.as_view(),
         name='restaurantreview_dine_detail_urlpattern'),
    path('dine/create/',
         DineCreate.as_view(),
         name='restaurantreview_dine_create_urlpattern'),
    path('dine/<int:pk>/delete/',
         DineDelete.as_view(),
         name='restaurantreview_dine_delete_urlpattern'),
    path('dine/<int:pk>/update/',
         DineUpdate.as_view(),
         name='restaurantreview_dine_update_urlpattern'),
    path('item/',
         ItemList.as_view(),
         name='restaurantreview_item_list_urlpattern'),
    path('item/<int:pk>/',
         ItemDetail.as_view(),
         name='restaurantreview_item_detail_urlpattern'),
    path('item/create/',
         ItemCreate.as_view(),
         name='restaurantreview_item_create_urlpattern'),
    path('item/<int:pk>/delete/',
         ItemDelete.as_view(),
         name='restaurantreview_item_delete_urlpattern'),
    path('item/<int:pk>/update/',
         ItemUpdate.as_view(),
         name='restaurantreview_item_update_urlpattern'),
    path('location/',
         LocationList.as_view(),
         name='restaurantreview_location_list_urlpattern'),
    path('location/<int:pk>/',
         LocationDetail.as_view(),
         name='restaurantreview_location_detail_urlpattern'),
    path('location/create/',
         LocationCreate.as_view(),
         name='restaurantreview_location_create_urlpattern'),
    path('location/<int:pk>/delete/',
         LocationDelete.as_view(),
         name='restaurantreview_location_delete_urlpattern'),
    path('location/<int:pk>/update/',
         LocationUpdate.as_view(),
         name='restaurantreview_location_update_urlpattern'),
    path('recipe/',
         RecipeList.as_view(),
         name='restaurantreview_recipe_list_urlpattern'),
    path('recipe/<int:pk>/',
         RecipeDetail.as_view(),
         name='restaurantreview_recipe_detail_urlpattern'),
    path('recipe/create/',
         RecipeCreate.as_view(),
         name='restaurantreview_recipe_create_urlpattern'),
    path('recipe/<int:pk>/delete/',
         RecipeDelete.as_view(),
         name='restaurantreview_recipe_delete_urlpattern'),
    path('recipe/<int:pk>/update/',
         RecipeUpdate.as_view(),
         name='restaurantreview_recipe_update_urlpattern'),
    path('rating/',
         RatingList.as_view(),
         name='restaurantreview_rating_list_urlpattern'),
    path('rating/<int:pk>/',
         RatingDetail.as_view(),
         name='restaurantreview_rating_detail_urlpattern'),
    path('rating/create/',
         RatingCreate.as_view(),
         name='restaurantreview_rating_create_urlpattern'),
    path('rating/<int:pk>/delete/',
         RatingDelete.as_view(),
         name='restaurantreview_rating_delete_urlpattern'),
    path('rating/<int:pk>/update/',
         RatingUpdate.as_view(),
         name='restaurantreview_rating_update_urlpattern'),

]
